export default [
  {
    ignores: ["**/node_modules/**", "**/dist/**", "**/*.min.js", "assets/vendor/**"],
  },
  {
    files: ["**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        console: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        fetch: "readonly",
        XMLHttpRequest: "readonly",
        WebSocket: "readonly",
        IntersectionObserver: "readonly",
        MutationObserver: "readonly",
        ResizeObserver: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        requestIdleCallback: "readonly",
        cancelIdleCallback: "readonly",
        AudioContext: "readonly",
        webkitAudioContext: "readonly",
        self: "readonly",
      },
    },
    rules: {
      "no-console": "warn",
      "no-debugger": "error",
      "no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      "no-var": "error",
      "prefer-const": "error",
      "eqeqeq": ["error", "always"],
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-with": "error",
      "no-script-url": "error",
      "no-loop-func": "error",
      "no-new-func": "error",
      "no-new-wrappers": "error",
      "consistent-return": "warn",
      "curly": ["error", "all"],
      "indent": ["warn", 2],
      "quotes": ["warn", "double", { avoidEscape: true }],
      "semi": ["error", "always"],
      "space-before-function-paren": ["warn", { anonymous: "always", named: "never", asyncArrow: "always" }],
      "no-trailing-spaces": "error",
      "no-multiple-empty-lines": ["warn", { max: 2, maxBOF: 0, maxEOF: 0 }],
      "keyword-spacing": "error",
      "comma-spacing": "error",
      "arrow-spacing": "error",
      "object-curly-spacing": ["warn", "always"],
      "array-bracket-spacing": ["warn", "never"],
      "no-param-reassign": "warn",
      "no-shadow": "warn",
    },
  },
  {
    files: ["gulpfile.cjs"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "commonjs",
      globals: {
        require: "readonly",
        module: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        process: "readonly",
      },
    },
  },
  {
    files: ["cloudflare/worker.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        fetch: "readonly",
      },
    },
  },
  {
    files: ["sw.js"],
    languageOptions: {
      globals: {
        self: "writable",
        caches: "readonly",
        Response: "readonly",
        Promise: "readonly",
      },
    },
  },
];
